version: '3'
services:
  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - www-data:/var/www/html/wordpress
    env_file:
      - .env
    ports:
      - 443:443
    restart: always


volumes:
  www-data:
    driver_opts:
      type: none
      device: /home/ahaifoul42/data/www-data
      o: bind

  